
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (1, 'EPS001' , 'Avenida Eldorado #69C-03 P-3' , '8301138310' , 'SSS COLMEDICA ENTIDAD PROMOTORA DE SALUD S.A.' , '3240290' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (2, 'EPS008' , 'Avenida 68 #49A-47' , '8600669427' , 'SSS CAJA DE COMPENSACION FAMILIAR COMPENSAR' , '4280666-4285244' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (3, 'EPS012' , 'Calle 5 # 6-63' , '8903030935' , 'SSS COMFENALCO VALLE' , '(092) 8854444-8830747-8803910-8862727' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (4, 'EPS015' , 'Avenida 19 #114-65 Piso 3' , '8605122376' , 'SSS SALUD COLPATRIA S.A.' , '6400310/11' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (5, 'EPS003' , 'Calle 73 #12-02 Piso 7º' , '8001409496' , 'SSS CAFESALUD EPS' , '3171820-2188977-2182892-2565543-2557885-2570579' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (6, 'EPS023' , 'Calle 86 A #14-17' , '8300097830' , 'SSS CRUZBLANCA S.A.' , '6446000-6446100 Ext. 1700' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (7, 'EPS017' , 'Carrera 13A #77A-63' , '8300035647' , 'SSS E.P.S. FAMISANAR LTDA. CAFAM COLSUBSIDIO' , '6500200' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (8, 'EPS005' , 'Calle 100 #11B-95' , '8002514406' , 'SSS E.P.S. SANITAS S.A.' , '6466080' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (9, 'EPS034' , 'Carrera 44 #5E-47 Barrio Tequendama     ' , '8050219842' , 'SSS SALUDCOLOMBIA EPS S.A.' , '(092) 5529364 (091)  2889409   -  2889465' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (10, 'EPS013' , 'Avenida 13 #109-20' , '8002501191' , 'SSS SALUDCOOP EPS' , '6001050 Ext. 1701 - 6290634' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (11, 'EPS033' , 'Av. Calle 40 A #13-06' , '8300741845' , 'SSS SALUDVIDA S.A. EPS' , '3274141-3203860' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (12, 'EPS018' , 'Avenida de las Américas     #23N-55' , '8050011572' , 'SSS SERVICIO OCCIDENTAL DE SALUD S.A. S.O.S.' , '(092) 6848686 Ext. 300 ó 306- 6614353' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (13, 'EPS026' , 'Carrera 26 #30-70' , '8040012735' , 'SSS SOLIDARIA DE SALUD SOLSALUD S.A.' , '(976) 352211 Ext. 122 ó 123 - 6350074' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (14, 'EPS016' , 'Carrera 13 #57-50 Piso 2' , '8050004271' , 'SSS COOMEVA EPS S.A.' , '(092) 3330000 Ext. 2708' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (15, 'EPS006' , 'Carrera 10 #64-28' , '8600138161' , 'SSS INSTITUTO DE SEGUROS SOCIALES' , '3437655 - 3437653' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (16, 'EPS020' , 'Avenida Eldorado #57-90' , '8999990260' , 'SSS CAPRECOM' , '2943080-2943004-2943131' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (17, 'EPS002' , 'Carrera 20 #109 -15' , '8001309074' , 'SSS SALUD TOTAL S.A. EPS ARS' , '6296660 al 70' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (18, 'EPS009' , 'Carrera 50 #53-43' , '8909008426' , 'SSS CAJA DE COMPENSACION FAMILIAR COMFENALCO ANTIOQUIA' , '(094) 5128363-5113133' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (19, 'EPS010' , 'Calle 54 #46-27 P-9 Torre Fundadores Clínica Medellín' , '8000887022' , 'SSS COMPAÑIA SURAMERICANA DE SERVICIOS DE SALUD S.A. SUSALUD' , '(094) 4938600-5110499-5132051' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (20, 'EPS014' , 'Calle 76 #11-52' , '8300064040' , 'SSS HUMANA VIVIR S.A. EPS' , '5460920-5462016-3133050/60/47' );
INSERT INTO SMB_EPS (ID_EPS, CODIGO_EPS,  DIRECCION_EPS, NIT_EPS, NOMBRE_EPS,TELEFONO_EPS) 
VALUES (21, 'EPS035' , 'Calle 100 #19-61 Piso 8' , '8300965131' , 'SSS REDSALUD ATENCION HUMANA EPS S.A.' , '6353459 - 6353538' );

drop sequence sq_eps;

create sequence sq_eps start with 22 nocache;

INSERT INTO SMB_AFP (ID_AFP, CODIGO_AFP, DIRECCION_AFP, NIT_AFP, NOMBRE_AFP,TELEFONO_AFP)
VALUES (1, '230301' , 'Carrera 13 No. 27-75 Torre B' , '8002248088' , 'SSS ADMINISTRADORA DE FONDOS DE PENSIONES Y CESANTIAS PORVENIR S.A.' , '');
INSERT INTO SMB_AFP (ID_AFP, CODIGO_AFP, DIRECCION_AFP, NIT_AFP, NOMBRE_AFP,TELEFONO_AFP)
VALUES (2, '25-11' , 'Carrera 10 No.64-28' , '8600138161' , 'SSS INSTITUTO DE SEGUROS SOCIALES' , '5223300');
INSERT INTO SMB_AFP (ID_AFP, CODIGO_AFP, DIRECCION_AFP, NIT_AFP, NOMBRE_AFP,TELEFONO_AFP)
VALUES (3, '25-4' , 'Avenida El Dorado No. 57-90' , '8999990260' , 'SSS CAPRECOM' , '2943131-2943004-2943080-2943333');
INSERT INTO SMB_AFP (ID_AFP, CODIGO_AFP, DIRECCION_AFP, NIT_AFP, NOMBRE_AFP,TELEFONO_AFP)
VALUES (4, '230801' , 'Carrera 7 No. 99-53 ' , '8002248278' , 'SSS FONDO DE PENSIONES SANTANDER' , '');
INSERT INTO SMB_AFP (ID_AFP, CODIGO_AFP, DIRECCION_AFP, NIT_AFP, NOMBRE_AFP,TELEFONO_AFP)
VALUES (5, '25-2' , 'Carrera 10 No. 90-35' , '8600073798' , 'SSS CAJA DE AUXILIOS Y DE PRESTACIONES DE ACDAC CAXDAC' , '6180287-6108682-6180011-6184400-6180339-6180402');
INSERT INTO SMB_AFP (ID_AFP, CODIGO_AFP, DIRECCION_AFP, NIT_AFP, NOMBRE_AFP,TELEFONO_AFP)
VALUES (6, '25-8' , 'Transversal 45 No. 41-53 CAN ' , '8999990103' , 'SSS CAJA NACIONAL DE PREVISION SOCIAL' , '018000910317-3155847-3155849-018000837006-2837001-2837201');
INSERT INTO SMB_AFP (ID_AFP, CODIGO_AFP, DIRECCION_AFP, NIT_AFP, NOMBRE_AFP,TELEFONO_AFP)
VALUES (7, '230904' , '.' , '8301251322' , 'SSS FONDO ALTERNATIVO DE PENSIONES SKANDIA' , '.');
INSERT INTO SMB_AFP (ID_AFP, CODIGO_AFP, DIRECCION_AFP, NIT_AFP, NOMBRE_AFP,TELEFONO_AFP)
VALUES (8, '25-3' , 'Carrera 10 No. 24-55 Pisos 2 y 3' , '8999997347' , 'SSS FONDO DE PREVISION SOCIAL DEL CONGRESO DE LA REPUBLICA' , '3415566');
INSERT INTO SMB_AFP (ID_AFP, CODIGO_AFP, DIRECCION_AFP, NIT_AFP, NOMBRE_AFP,TELEFONO_AFP)
VALUES (9, '230901' , 'Avenida 19 No. 113-30' , '8002530552' , 'SSS FONDO OBLIGATORIO DE PENSIONES SKANDIA' , '(1)6192939 - 6127177 - 5923405');
INSERT INTO SMB_AFP (ID_AFP, CODIGO_AFP, DIRECCION_AFP, NIT_AFP, NOMBRE_AFP,TELEFONO_AFP)
VALUES (10, '230201' , 'Calle 49 No. 63-100' , '8002297390' , 'SSS PROTECCION FONDO DE PENSIONES OBLIGATORIAS' , '(051)2302666');
INSERT INTO SMB_AFP (ID_AFP, CODIGO_AFP, DIRECCION_AFP, NIT_AFP, NOMBRE_AFP,TELEFONO_AFP)
VALUES (11, '25-7' , 'Calle 55 No. 49-100 Sector Parque Bolivar' , '8002162780' , 'SSS PENSIONES DE ANTIOQUIA' , '5141415');
INSERT INTO SMB_AFP (ID_AFP, CODIGO_AFP, DIRECCION_AFP, NIT_AFP, NOMBRE_AFP,TELEFONO_AFP)
VALUES (12, '230501' , 'Carrera 11 No. 87-51 Pisos 7 al 9' , '8002319671' , 'SSS FONDO DE PENSIONES HORIZONTE' , '6280220');
INSERT INTO SMB_AFP (ID_AFP, CODIGO_AFP, DIRECCION_AFP, NIT_AFP, NOMBRE_AFP,TELEFONO_AFP)
VALUES (13, '231001' , 'Calle 67 No. 7-94 Pisos 3, 6, 10, 11, 14 al PH' , '8002279406' , 'SSS FONDO DE PENSIONES OBLIGATORIAS COLFONDOS' , '3766616');

drop sequence sq_afp;

create sequence sq_afp start with 14 nocache;

INSERT INTO SMB_ARL (ID_ARL, CODIGO_ARL, DIRECCION_ARL, NIT_ARL, NOMBRE_ARL, TELEFONO_ARL)
VALUES (1, '14-25' , 'Avenida El Dorado No. 69C - 03 Piso 5' , '8002261753' , 'SSS COLMENA RIESGOS PROFESIONALES S.A.' , '071 - 324 11 11 y  2502' );
INSERT INTO SMB_ARL (ID_ARL, CODIGO_ARL, DIRECCION_ARL, NIT_ARL, NOMBRE_ARL, TELEFONO_ARL)
VALUES (2, '14-5' , 'Carrera 11 No. 93 - 46 - Piso 9' , '8600025286' , 'SSS COMPAÑIA AGRICOLA DE SEGUROS DE VIDA S.A.' , '071 - 635 08 87' );
INSERT INTO SMB_ARL (ID_ARL, CODIGO_ARL, DIRECCION_ARL, NIT_ARL, NOMBRE_ARL, TELEFONO_ARL)
VALUES (3, '14-4' , 'Carrera 7 No. 24 - 89 ' , '8600021839' , 'SSS SEGUROS DE VIDA COLPATRIA S.A.' , '071 - 336 46 77' );
INSERT INTO SMB_ARL (ID_ARL, CODIGO_ARL, DIRECCION_ARL, NIT_ARL, NOMBRE_ARL, TELEFONO_ARL)
VALUES (4, '14-19' , 'Carrera 11 No. 90 - 20 ' , '8600091744' , 'SSS SEGUROS DE VIDA DEL ESTADO S.A.' , '071 - 218 30 18' );
INSERT INTO SMB_ARL (ID_ARL, CODIGO_ARL, DIRECCION_ARL, NIT_ARL, NOMBRE_ARL, TELEFONO_ARL)
VALUES (5, '14-7' , 'Carrera 10 No. 16 - 39 ' , '8600025032' , 'SSS SEGUROS BOLIVAR S.A.' , '071 - 341 00 77' );
INSERT INTO SMB_ARL (ID_ARL, CODIGO_ARL, DIRECCION_ARL, NIT_ARL, NOMBRE_ARL, TELEFONO_ARL)
VALUES (6, '14-8' , 'Carrera 7 No. 74 - 21 Piso 1' , '8600221375' , 'SSS COMPAÑÍA DE SEGUROS DE VIDA AURORA S.A.' , '071 - 212 74 06' );
INSERT INTO SMB_ARL (ID_ARL, CODIGO_ARL, DIRECCION_ARL, NIT_ARL, NOMBRE_ARL, TELEFONO_ARL)
VALUES (7, '14-23' , 'Carrera 7 No. 26 - 20 Piso 5' , '8600111536' , 'SSS LA PREVISORA VIDA S.A. COMPAÑÍA DE SEGUROS' , '071 - 232 46 73 ' );
INSERT INTO SMB_ARL (ID_ARL, CODIGO_ARL, DIRECCION_ARL, NIT_ARL, NOMBRE_ARL, TELEFONO_ARL)
VALUES (8, '14-17' , 'Carrera 13 No. 27 - 47 Piso 22  Y 23' , '8605036173' , 'SSS SEGUROS DE VIDA ALFA S.A.' , '071 - 287 59 11' );
INSERT INTO SMB_ARL (ID_ARL, CODIGO_ARL, DIRECCION_ARL, NIT_ARL, NOMBRE_ARL, TELEFONO_ARL)
VALUES (9, '25-10' , 'Avenida 15 No 100 - 43 ' , '8600138161' , 'SSS INSTITUTO DE SEGUROS SOCIALES' , '071 - 523 27 20 ' );
INSERT INTO SMB_ARL (ID_ARL, CODIGO_ARL, DIRECCION_ARL, NIT_ARL, NOMBRE_ARL, TELEFONO_ARL)
VALUES (10, '14-18' , 'Calle 71 A No. 6 - 30 Piso 14' , '8600086457' , 'SSS LIBERTY SEGUROS DE VIDA S.A.' , '071 - 346 20 79' );
INSERT INTO SMB_ARL (ID_ARL, CODIGO_ARL, DIRECCION_ARL, NIT_ARL, NOMBRE_ARL, TELEFONO_ARL)
VALUES (11, '14-1' , 'Carrera 13 No 29 - 24' , '8600274041' , 'SSS ASEGURADORA DE VIDA COLSEGUROS S.A.' , '071 - 218 30 18' );
INSERT INTO SMB_ARL (ID_ARL, CODIGO_ARL, DIRECCION_ARL, NIT_ARL, NOMBRE_ARL, TELEFONO_ARL)
VALUES (12, '14-28' , 'Carrera 50 No. 52 - 50 Piso 10 Club Unión' , '8002561619' , 'SSS SURATEP SA' , '074 - 511 35 45' );
INSERT INTO SMB_ARL (ID_ARL, CODIGO_ARL, DIRECCION_ARL, NIT_ARL, NOMBRE_ARL, TELEFONO_ARL)
VALUES (13, '14-26' , 'Calle 72 No 7 - 64 ' , '8002408820' , 'SSS BBVA SEGUROS DE VIDA SA' , '071 - 312 26 30' );
INSERT INTO SMB_ARL (ID_ARL, CODIGO_ARL, DIRECCION_ARL, NIT_ARL, NOMBRE_ARL, TELEFONO_ARL)
VALUES (14, '14-29' , 'Calle 19 No. 6 - 68 Piso 11' , '8300086861' , 'SSS LA EQUIDAD SEGUROS DE VIDA' , '071 - 284 19 00' );

drop sequence sq_arl;

create sequence sq_arl start with 15 nocache;

INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (1 ,'1', CURRENT_DATE, 1,'830070577-8' ,'SOCIEDAD INTERNACIONAL DE TRANSPORTE MASIVO SA CIU','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (2 ,'2', CURRENT_DATE, 1,'2-5' ,'EXPRES DEL FUTURO S.A.','EXPRESS DEL FUTURO','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (3 ,'3', CURRENT_DATE, 1,'3-2' ,'SISTEMA INTEGRADO DE TRANSPORTE S.A. SI99','SI99','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (4 ,'1003', CURRENT_DATE, 1,'830129995-1' ,'SI-03 S.A.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (5 ,'1004', CURRENT_DATE, 1,'1004-4' ,'METROBUS SA','METROBUS','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (6 , '1005', CURRENT_DATE, 1,'830106777-1' ,'TRANSMASIVO SA','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (7 ,'1006', CURRENT_DATE, 1,'830111317-7' ,'SISTEMAS OPERATIVOS MOVILES SOMOS K S.A.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (8 ,'1007', CURRENT_DATE, 1,'830115770-9' ,'COMPANÍA MULTINACIONAL DE TRANSPORTE MASIVO -CONNEXION','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (9 ,'1008', CURRENT_DATE, 1,'830132034-8' ,'TRANSPORTE ALIMENTADOR DE OCCIDENTE S.A . - TAO S.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (10 ,'1009', CURRENT_DATE, 1,'900359974-5' ,'ALNORTE FASE 2 S.A.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (11 ,'1011', CURRENT_DATE, 1,'830132853-3' ,'U.T. ALCAPITAL FASE 2','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (12 ,'1999', CURRENT_DATE, 1,'830132151-1' ,'ETMA S.A.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (13 ,'9000', CURRENT_DATE, 1,'860002434-2' ,'BUSES AMARILLOS Y ROJO S.A.','BARSA S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (14 ,'9010', CURRENT_DATE, 1,'860029490-2' ,'BUSES ROJOS LTDA.','BUSES ROJOS','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (15 ,'9020', CURRENT_DATE, 1,'860028731-8' ,'COOPERATIVA CONTINENTAL DE TRANSPORTADORES LTDA.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (16 ,'9030', CURRENT_DATE, 1,'860508185-6' ,'PROMOTORA DE TRANSPORTES UNIVERSO S.C.A.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (17 ,'9040', CURRENT_DATE, 1,'860025858-0' ,'COOPERATIVA DE TRANSPORTADORES LA NACIONAL LTDA.','COONAL','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (18 ,'9050', CURRENT_DATE, 1,'860032905-8' ,'COOPERATIVA DE TRANSPORTADORES BUSES VERDES LTDA.','COOP BUSES VERDES','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (19 ,'9060', CURRENT_DATE, 1,'860020381-7' ,'COOPERATIVA NACIONAL DE TRANSPORTADORES','COPENAL','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (20 ,'9065', CURRENT_DATE, 1,'860507283-5' ,'COOPERATIVA INTEGRAL DE TRANSPORTADORES MIXTOS DE','COOTRANSABASTOS','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (21 ,'9070', CURRENT_DATE, 1,'860016499-1' ,'COOPERATIVA INTEGRAL DE TRANSPORTADORES DE NIZA L','COOTRANSNIZA LTDA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (22 ,'9075', CURRENT_DATE, 1,'830136587-7' ,'CITY TAXI SA','CITY TAXI','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (23 ,'9080', CURRENT_DATE, 1,'860006119-5' ,'COMPAÑIA METROPOLITANA DE TRANSPORTES S.A.','METROPOLITANA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (24 ,'9090', CURRENT_DATE, 1,'860027234-4' ,'COMPAÑIA NACIONAL DE MICROBUSES S.A.','COMNALMICROS','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (25 ,'9100', CURRENT_DATE, 1,'860022022-7' ,'COOPERATIVA DE TRANSPORTADORES UNIDOS DEL DISTRITO','COOTRAUNIDOS','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (26 ,'9110', CURRENT_DATE, 1,'860028285-4' ,'EXPRESO BOGOTANO S.A.','EXBOSA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (27 ,'9120', CURRENT_DATE, 1,'860032029-0' ,'EMPRESA VECINAL DE TRANSPORTADORES DE SUBA S.A.','EVETRANS S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (28 ,'9130', CURRENT_DATE, 1,'860020096-2' ,'COOPERATIVA NACIONAL MULTIACTIVA DE LA CONFEDERACI','COONALCETECE','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (29 ,'9140', CURRENT_DATE, 1,'860026738-1' ,'FLOTA USAQUEN S.A.','FU','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (30 ,'9150', CURRENT_DATE, 1,'860009619-1' ,'NUEVA COOPERATIVA DE BUSES AZULES LTDA.','BUSES AZULES','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (31 ,'9160', CURRENT_DATE, 1,'860028203-0' ,'NUEVA TRANSPORTADORA DE BOGOTA S.A.','NUEVATRANS','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (32 ,'9170', CURRENT_DATE, 1,'860006170-1' ,'REPUBLICANA DE TRANSPORTES S.A.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (33 ,'9180', CURRENT_DATE, 1,'860010171-4' ,'TRANSPORTES RAPIDO PENSILVANIA S.A.','TRP','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (34 ,'9190', CURRENT_DATE, 1,'860002950-1' ,'SOCIEDAD IMPORTADORA Y DISTRIBUIDORA AUTOMOTORA S.','SIDAUTO','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (35 ,'9200', CURRENT_DATE, 1,'860009056-3' ,'TRANSPORTES BERMÚDEZ S.A','TRANSBECARGA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (36 ,'9210', CURRENT_DATE, 1,'860002997-7' ,'TRANSPORTES FLOTA BLANCA S.A.','TFB','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (37 ,'9220', CURRENT_DATE, 1,'860005087-3' ,'TRANSPORTES PANAMERICANOS S.A.','TRANSPANAMERICANOS','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (38 ,'9230', CURRENT_DATE, 1,'860006875-5' ,'TRANSPORTES URBANOS SAMPER MENDOZA','BUSES BLANCOS S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (39 ,'9240', CURRENT_DATE, 1,'860005088-0' ,'TRANSPORTES SANTA LUCIA S.A.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (40 ,'9250', CURRENT_DATE, 1,'860002241-8' ,'UNION COMERCIAL DE TRANSPORTES S.A.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (41 ,'9260', CURRENT_DATE, 1,'860005446-4' ,'SOCIEDAD UNIVERSAL AUTOMOTORA DE TRANSPORTES S.A.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (42 ,'9270', CURRENT_DATE, 1,'800015898-3' ,'ASOC. PROPIETARIOS DE TAXIS AEROPUERTO EL DORADO','ASTAXDORADO','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (43 ,'9275', CURRENT_DATE, 1,'900038598-1' ,'MOVITAX S.A.S','MOVITAX S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (44 ,'9280', CURRENT_DATE, 1,'860045813-5' ,'EXPRESO SUR ORIENTE S.A.','EXPRESUR','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (45 ,'9290', CURRENT_DATE, 1,'800156391-7' ,'COOPERATIVA MULTIACTIVA SANTAFE DE BOGOTA','SANTAFE DE BOGOTA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (46 ,'9315', CURRENT_DATE, 1,'800151556-2' ,'UNION AUTOMOTORA DE URBANOS ESPECIALES UNITURS LTD','LINEAS UNITURS LTDA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (47 ,'9320', CURRENT_DATE, 1,'860007701-3' ,'COMPAÑIA DE TAXIS VERDES S.A.','CIA DE TAXIS VERDES S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (48 ,'9330', CURRENT_DATE, 1,'860004277-1' ,'EMPRESA DE TRANSPORTES TAXI ESTRELLA S.A.','TESA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (49 ,'9340', CURRENT_DATE, 1,'860023460-4' ,'COOPERATIVA TRANSPORTADORA BOGOTA KENNEDY LTDA.','COOTRANSKENNEDY','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (50 ,'9350', CURRENT_DATE, 1,'860013844-4' ,'COOPERATIVA ASOCIACIÓN DE TANSPORTADORES DE COLOMB','COOPTELETAXI','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (51 ,'9360', CURRENT_DATE, 1,'800158965-3' ,'SERVICIO TRANSPORTES URBANOS DE LUJO S.A.','TRANSERVILUJO S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (52 ,'9370', CURRENT_DATE, 1,'860030632-3' ,'COOPERATIVA DE TRANSP. RADIO TAXI LTDA','COOTRATAXI','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (53 ,'9380', CURRENT_DATE, 1,'860008334-5' ,'EMPRESA DE TRANSPORTES COPER TAX S.A.','COPER TAX S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (54 ,'9390', CURRENT_DATE, 1,'860005105-9' ,'EMPRESA DE TRANSPORTES GRAN TAX S.A.','GRAN TAX','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (55 ,'9391', CURRENT_DATE, 1,'830506876-9' ,'CAR TAXIS S.A.','CAR TAXIS','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (56 ,'9400', CURRENT_DATE, 1,'860035920-4' ,'NUEVO TAXI MIO S.A.','NUEVO TAXI MIO','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (57 ,'9410', CURRENT_DATE, 1,'860005066-8' ,'REAL TRANSPORTADORA S.A.','RADIO REAL','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (58 ,'9420', CURRENT_DATE, 1,'860047560-6' ,'SOCIEDAD TRANSPORTADORA DE LOS ANDES S.A.','SOTRANDES','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (59 ,'9430', CURRENT_DATE, 1,'860004942-5' ,'TRANSPORTES DE COLOMBIA S.A.','TRANSCOL','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (60 ,'9440', CURRENT_DATE, 1,'860016246-5' ,'TAXI EL VOLANTE S.A.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (61 ,'9450', CURRENT_DATE, 1,'860004946-2' ,'TAXI PERLA S.A.','TAXI PERLA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (62 ,'9460', CURRENT_DATE, 1,'860002973-6' ,'TAXI ROXI INTERNACIONAL S.A','TAXI ROXI S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (63 ,'9470', CURRENT_DATE, 1,'860005337-1' ,'TRANSPORTES FONTIBON S.A.','TRANSFONTIBON','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (64 ,'9490', CURRENT_DATE, 1,'860045165-0' ,'COOPERATIVA INTEGRAL DE TRANSPORTADORES EL CÓNDOR','COOINTRACÓNDOR LTDA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (65 ,'9520', CURRENT_DATE, 1,'860050333-1' ,'COOPERATIVA INTEGRAL DE TRANSPORTADORES PENSILVANI','COOTRANSPENSILVANIA CITP','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (66 ,'9530', CURRENT_DATE, 1,'860036225-6' ,'EXPRESO DEL PAIS S.A.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (67 ,'9560', CURRENT_DATE, 1,'860038269-9' ,'PROMOCIONES Y TRANSPORTES TURISTICOS PROTURISMO','PROTURISMO S.A','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (68 ,'9570', CURRENT_DATE, 1,'860047989-1' ,'COOPERATIVA DE CONDUCTORES Y TRANSPORTADORES DE L','COCEVES','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (69 ,'9590', CURRENT_DATE, 1,'860055942-1' ,'TRANSPORTES NUEVO HORIZONTE S.A','TRANS. NUEVO HORIZONTE','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (70 ,'9635', CURRENT_DATE, 1,'800166850-9' ,'TRANSPORTES MODELO LTDA.','TRANSMODELO','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (71 ,'9640', CURRENT_DATE, 1,'860045513-0' ,'UNION COOPERATIVA DE TRABAJADORES DEL TRANSPORTE L','UCOTRANS','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (72 ,'9670', CURRENT_DATE, 1,'800089047-0' ,'COOPERATIVA DE TRANSPORTADORES SOCORRO.','COOTRANSOCORRO','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (73 ,'9700', CURRENT_DATE, 1,'860063061-1' ,'COOPERATIVA DISTRITAL INTEGRAL DE TRANSPORTES LTDA.','COODILTRA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (74 ,'9710', CURRENT_DATE, 1,'860502253-1' ,'UNION COLOMBIANA DE BUSES S.A.','UCOLBUS','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (75 ,'9730', CURRENT_DATE, 1,'800145640-9' ,'RADIO TAXI AUTOLAGOS S.A.','AUTOLAGOS','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (76 ,'9735', CURRENT_DATE, 1,'800166581-2' ,'TAXI MOVIL QAP S.A.','TAXI MOVIL QAP','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (77 ,'9740', CURRENT_DATE, 1,'860508938-3' ,'RADIO TAXI INTERNACIONAL.S.A','RADIO TAXI INTERNACIONAL','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (78 ,'9745', CURRENT_DATE, 1,'800174909-1' ,'TAX EXPRESS S.A.','TAX EXPRESS','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (79 ,'9750', CURRENT_DATE, 1,'860403373-2' ,'COOP. MULTIACTIVA DE TRANSPORTADORES LTDA','RADIO TAXI COOMFETRANS','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (80 ,'9755', CURRENT_DATE, 1,'800081143-3' ,'SUPER TAXI S.A.','SUPER TAXI','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (81 ,'9760', CURRENT_DATE, 1,'860048954-9' ,'COOPERATIVA INTEGRAL DE TRANSPORTADORES DE BOSA','COOTRANSBOSA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (82 ,'9765', CURRENT_DATE, 1,'800183946-9' ,'TRANSPORTES COMPUTAXI S.A.','COMPUTAXI S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (83 ,'9830', CURRENT_DATE, 1,'860531135-4' ,'RADIO TAXI AEROPUERTO S.A.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (84 ,'9840', CURRENT_DATE, 1,'860531777-2' ,'TAXATELITE S.A.','TAXATELITE','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (85 ,'9855', CURRENT_DATE, 1,'800087246-0' ,'COOPERATIVA DE TRANSPORTADORES DEL NORTE','COOTRANSNORTE','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (86 ,'9860', CURRENT_DATE, 1,'830001075-8' ,'TELECLUB LIMITADA','TELECLUB','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (87 ,'9910', CURRENT_DATE, 1,'860515036-6' ,'EXPRESO IMPERIAL S.A.','EXIMSA S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (88 ,'9940', CURRENT_DATE, 1,'800007282-4' ,'TRANSPORTES RADIO TAXI CONFORT S.A.','TRANSCONFORT S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (89 ,'9960', CURRENT_DATE, 1,'892000625-7' ,'TRANSPORTES ARIMENA S.A.','ARIMENA S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (90 ,'9970', CURRENT_DATE, 1,'800024569-4' ,'UNION TRANSPORTADORA NORTE Y SUR S.A.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (91 ,'9971', CURRENT_DATE, 1,'800162378-5' ,'TRANSPORTES DISTRITO CAPITAL S.A.','T.D.C. S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (92 ,'9979', CURRENT_DATE, 1,'830141357-1' ,'TAXIS YA S.A.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (93 ,'9980', CURRENT_DATE, 1,'800046952-7' ,'SOCIEDAD TRANSPORTADORA MIXTA URBANA DE BOGOTA','SOTRANSMIUR S. A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (94 , '9981', CURRENT_DATE, 1,'800114823-7' ,'COOPERATIVA MULTIACTIVA ZONAL DE TRANSPORTES BOSA','COOPZOBOSA LTDA.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (95 ,'9982', CURRENT_DATE, 1,'800068562-2' ,'COOPERATIVA DE TRANSPORTADORES AURES LTDA.','COOTRAURES LTDA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (96 ,'9983', CURRENT_DATE, 1,'800107777-7' ,'COMUNITARIA DE TRANSPORTES DE SUBA S.A.','COTRANSUBA S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (97 ,'9984', CURRENT_DATE, 1,'800106536-4' ,'COOPERATIVA DE TRANSPORTADORES DE FONTIBON','COOTRANSFONTIBON','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (98 ,'9985', CURRENT_DATE, 1,'860053315-2' ,'COOPERATIVA MULTIACTIVA DE LOS TRABAJADORES TRANSP','COOTRAPAN','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (99 ,'9986', CURRENT_DATE, 1,'800092942-9' ,'COOPERATIVA DE TRANSPORTADORES LOS MOLINOS LTDA.','COOTRANSMOLINOS','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (100 ,'9987', CURRENT_DATE, 1,'800070335-3' ,'COOPERATIVA DE TRANSPORTADORES DE BOGOTÁ LTDA.','COOTRANSBOGOTA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (101 ,'9988', CURRENT_DATE, 1,'800087517-1' ,'LINEAS ESPECIALES DE TRANSPORTE ANDINO','TRANSANDINO S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (102 ,'9989', CURRENT_DATE, 1,'800094986-1' ,'COOPERATIVA DE TRANSPORTES CERRO NORTE LTDA.','COOTRASCENORTE LTDA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (103 ,'9990', CURRENT_DATE, 1,'800033686-6' ,'COOPERATIVA DE TRANSPORTE DE VISTA HERMOSA LTDA.','VISTA HERMOSA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (104 ,'9991', CURRENT_DATE, 1,'800089509-1' ,'COOPERATIVA DE TRANSPORTADORES CIUDAD BOLÍVAR LTDA.','COOTRANSBOLIVAR','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (105 ,'9992', CURRENT_DATE, 1,'800086482-8' ,'LINEAS ESPECIALES DE TRANSPORTE NUEVO MILENIO S.A.','T.N.M. MILENIOS S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (106 ,'9993', CURRENT_DATE, 1,'800087921-4' ,'TRANSPORTES CALERO LTDA.','TRANSCALERO','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (107 ,'9994', CURRENT_DATE, 1,'800089388-7' ,'TRANSPORTE AUTOMOTOR MODERNO PUBLICO ASOCIADO DIST','TAMPA DC SAS','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (108 ,'9996', CURRENT_DATE, 1,'800087573-4' ,'COOPERATIVA INTEGRAL DE TRANSPORTES LA FLORIDA LTDA.','COOTRANSFLORIDA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (109 ,'9998', CURRENT_DATE, 1,'800027662-5' ,'AUTO TAXI EJECUTIVO S.A.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (110 ,'9999', CURRENT_DATE, 1,'800188528-6' ,'TRANSPORTES CARROS DEL SUR S.A.','TRANSCARD S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (111 ,'11245', CURRENT_DATE, 1,'830104827-1' ,'TAXIS ATH S.A','TAXIS ATH','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (112 ,'11836', CURRENT_DATE, 1,'800245843-6' ,'TAXIS TELECLUB S.A.','TAXIS TELECLUB S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (113 ,'11896', CURRENT_DATE, 1,'830501719-8' ,'AUTO TAXI COLOMBIA LTDA','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (114 ,'11906', CURRENT_DATE, 1,'830132103-8' ,'CITY MOVIL S.A','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (115 ,'11944', CURRENT_DATE, 1,'900042280-0' ,'TAXIS CAB','TAXIS CAB','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (116 ,'11950', CURRENT_DATE, 1,'900045751-1' ,'TAXIVISION LTDA','TAXIVISION LTDA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (117 ,'11972', CURRENT_DATE, 1,'900032610-5' ,'CELUTAXI AEROPUERTO S.A.','CELUTAX','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (118 ,'11973', CURRENT_DATE, 1,'830505382-8' ,'TRANSPORTES @ LINEA E.U','@','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (119 ,'11982', CURRENT_DATE, 1,'900076006-5' ,'ALO TAXIS S.A.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (120 ,'11989', CURRENT_DATE, 1,'830116785-3' ,'SOCIEDAD DE TAXISTAS UNIDOS STU S.A.','STU S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (121 ,'11990', CURRENT_DATE, 1,'900060655-5' ,'TAXIS LIBRES BOGOTA S.A.','TAXIS LIBRES S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (122 ,'11997', CURRENT_DATE, 1,'900029030-2' ,'AIR TAXIS S.A.','AIR TAXIS SA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (123 ,'12039', CURRENT_DATE, 1,'900063849-0' ,'TAXI BOGOTA ONLINE','TAXI BOGOTA ONLINE','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (124 ,'13051', CURRENT_DATE, 1,'900068195-5' ,'TRANSMOPAQ S.A','TRANSMOPAQ','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (125 ,'14042', CURRENT_DATE, 1,'900174377-2' ,'TAXIS 2222222 S.A.','t2','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (126 ,'14106', CURRENT_DATE, 1,'900173918-2' ,'LIBER TAX S.A.','LT','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (127 ,'14119', CURRENT_DATE, 1,'900252354-8' ,'TAXIS A LA MANO','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (128 ,'14120', CURRENT_DATE, 1,'900298395-8' ,'OPERADOR TAX COLOMBIA S.A.S.','TAX COLOMBIA S.A.S','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (129 ,'14141', CURRENT_DATE, 1,'900358353-7' ,'NUEVA EMPRESA DE TAXIS S.A.S.','NE','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (130 ,'14144', CURRENT_DATE, 1,'0-1' ,'RENTAXI S.A.','','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (131 ,'14157', CURRENT_DATE, 1,'900382572-4' ,'TAXTOTAL S.A.S.','TAXTOTAL S.A.S.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (132 ,'14158', CURRENT_DATE, 1,'900053917-0' ,'RENTAXI S.A.','RENTAXI S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (133 ,'14159', CURRENT_DATE, 1,'800233968-6' ,'COMUNICACIONES TECH Y TRANSPORTE S.A','COTECH S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (134 ,'14160', CURRENT_DATE, 1,'830077886-0' ,'RAPTOR EXPRES LTDA','RAPTOR EXPRES LTDA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (135 ,'14171', CURRENT_DATE, 1,'800191773-5' ,'TAXITEL S.A.','TAXITEL S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (136 ,'14178', CURRENT_DATE, 1,'900394791-2' ,'MASIVO CAPITAL S.A.S.','MASIVO CAPITAL S.A.S.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (137 ,'14181', CURRENT_DATE, 1,'800249814-0' ,'RADIO TAXIS AMARILLOS','RTA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (138 ,'14196', CURRENT_DATE, 1,'900560771-7' ,'TRANSPORTE INTEGRAL PLATINIUM LTDA','TRANSPLATINIUM','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (139 ,'14198', CURRENT_DATE, 1,'900602929-5' ,'TAXI ESTRELLA S.A.','TAXIESTRELLA S.A.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (140 ,'14209', CURRENT_DATE, 1,'900526151-7' ,'DIGITAX SAS','DIGITAX SAS','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (141 ,'14212', CURRENT_DATE, 1,'800210814-1' ,'FONTICOCHES.LTDA','FONTICOCHES.LTDA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (142 ,'14214', CURRENT_DATE, 1,'900699521-0' ,'OPERADORA DE TRANSPORTE DE COLOMBIA TAXI CUPOS S.A.S','Taxi cupos','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (143 ,'14215', CURRENT_DATE, 1,'900592904-7' ,'TAXIS LOS CORRECAMINOS S.A.S.','TAXIS LOS CORRECAMINOS S.A.S.','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (144 ,'14232', CURRENT_DATE, 1,'900646755-1' ,'YELLOW CAB 100% SAFETY LIMITADA','YELLOW CAB 100% SAFETY LIMITADA','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (145 ,'14233', CURRENT_DATE, 1,'900498351-2' ,'TRANSMIO S.A.S','TRANSMIO S.A.S','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (146 ,'14253', CURRENT_DATE, 1,'830133622-3' ,'SUTAXI LTDA','SUTAXI','' ); 
INSERT INTO SMI_EMPRESA  (ID_EMPRESA, CODIGO_EMPRESA, FECHA_MODIFICA, ID_ESTADO, ID_NIT_EMPRESA, NOMBRE_RAZON_SOCIAL, SIGLA_EMPRESA, USUARIO_MODIFICA)
VALUES (147 ,'14257', CURRENT_DATE, 1,'900633991-5' ,'LUMITAX S A S','LUMITAX','' ); 

drop sequence sq_empresa;

create sequence sq_empresa start with 148 nocache;

INSERT INTO SMB_TARJETA_CONTROL_ESTADO (ID, activo, descripcion) VALUES ('1', 1, 'Expedida');
INSERT INTO SMB_TARJETA_CONTROL_ESTADO (ID, activo, descripcion) VALUES ('2', 1, 'Refrendado');
INSERT INTO SMB_TARJETA_CONTROL_ESTADO (ID, activo, descripcion) VALUES ('3', 1, 'Cancelado');
INSERT INTO SMB_TARJETA_CONTROL_ESTADO (ID, activo, descripcion) VALUES ('4', 1, 'Sin vigencia por cambio');

drop sequence sq_tarjeta_control;

create sequence sq_tarjeta_control start with 4 nocache;

INSERT INTO SMB_PERFIL (ID_PERFIL, DESCRIPCION_PERFIL, ID_ESTADO) VALUES (1, 'ROLE_EXTERNAL', 1);
INSERT INTO SMB_PERFIL (ID_PERFIL, DESCRIPCION_PERFIL, ID_ESTADO) VALUES (2, 'ROLE_SDM', 1);

drop sequence sq_perfil;

create sequence sq_perfil start with 3 nocache;

INSERT INTO SMB_TIPO_USUARIO (ID_TIPO_USUARIO, DESCRIPCION_TIPO) VALUES (1, 'EXTERNO');
INSERT INTO SMB_TIPO_USUARIO (ID_TIPO_USUARIO, DESCRIPCION_TIPO) VALUES (2, 'INTERNO');

drop sequence sq_tipo_usuario;

create sequence sq_tipo_usuario start with 3 nocache;

INSERT INTO SMB_TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO, DESCRIPCION_TIPODOC, HOMOLOGA_DUUPS)
VALUES (1,'Cédula de Ciudadanía', 'CC');
INSERT INTO SMB_TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO, DESCRIPCION_TIPODOC, HOMOLOGA_DUUPS)
VALUES (2,'Cédula de Extranjería', 'CE');

drop sequence sq_tipo_documento;

create sequence sq_tipo_documento start with 3 nocache;

INSERT INTO SMI_PERSONA (ID_PERSONA, ID_ESTADO, NOMBRES) VALUES (1,1, 'Usuario');

drop sequence sq_persona;

create sequence sq_persona start with 2 nocache;

--Password Q1w2e3r4t5
INSERT INTO SMI_USUARIO (ID_USUARIO, CLAVE_USUARIO, ID_PERSONA, ID_ESTADO, FECHA_MODIFICA, ID_TIPO_USUARIO, LOGIN_USUARIO, ID_PERFIL) 
VALUES (1, 'sZUy9aPQBH5SWD0yoPskX0rbmtnHla30zgoTXcnRfEU=', 1, 1, CURRENT_DATE,1,'admin', 2);

drop sequence sq_usuario;

create sequence sq_usuario start with 2 nocache;

commit;



