
UPDATE SMB_PARAMETRO_SIMUR SET VALOR_PARAMETRO = '11001000' WHERE CODIGO_PARAMETRO = 'simur.municipio.solicitud.duups';

DELETE FROM SMB_PARAMETRO_SIMUR 
WHERE  ID_PARAMETRO = 24;

INSERT INTO SMB_PARAMETRO_SIMUR (ID_PARAMETRO, CODIGO_PARAMETRO, DESCRIPCION_PARAMETRO, ID_ESTADO, VALOR_PARAMETRO) 
VALUES (24, 'CABECERA_IPCLIENTE_DUUPS', 'Cabecera ip Cliente Duups', 1, '192.168.100.67');

DELETE FROM SMB_PARAMETRO_SIMUR 
WHERE  ID_PARAMETRO = 25;

INSERT INTO SMB_PARAMETRO_SIMUR (ID_PARAMETRO, CODIGO_PARAMETRO, DESCRIPCION_PARAMETRO, ID_ESTADO, VALOR_PARAMETRO) 
VALUES (25, 'CABECERA_PASSWORD_DUUPS', 'Cabecera password Duups', 1, 'ws2017.');

DELETE FROM SMB_PARAMETRO_SIMUR 
WHERE  ID_PARAMETRO = 26;

INSERT INTO SMB_PARAMETRO_SIMUR (ID_PARAMETRO, CODIGO_PARAMETRO, DESCRIPCION_PARAMETRO, ID_ESTADO, VALOR_PARAMETRO) 
VALUES (26, 'CABECERA_USUARIO_DUUPS', 'Cabecera usuario Duups', 1, 'wsduups');

drop sequence sq_parametro;

create sequence sq_parametro start with 27 nocache;

commit;