INSERT INTO SMB_PARAMETRO_SIMUR (ID_PARAMETRO, CODIGO_PARAMETRO, DESCRIPCION_PARAMETRO, ID_ESTADO, VALOR_PARAMETRO) 
VALUES (31, 'CODIGO_ORIGEN_SIRC_DUUPS', 'Codigo origen sirc duups', 1, '15');
commit;
