
package co.gov.movilidadbogota.wsOLD.duups;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioReceptorPersonaDUUPSService", targetNamespace = "http://impl.servicioreceptorpersonaduups.sdm.com/", wsdlLocation = "http://192.168.100.67:8080/PersonasDUUPS/ServicioReceptorPersonaDUUPS?wsdl")
public class ServicioReceptorPersonaDUUPSService
    extends Service
{

    private final static URL SERVICIORECEPTORPERSONADUUPSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIORECEPTORPERSONADUUPSSERVICE_EXCEPTION;
    private final static QName SERVICIORECEPTORPERSONADUUPSSERVICE_QNAME = new QName("http://impl.servicioreceptorpersonaduups.sdm.com/", "ServicioReceptorPersonaDUUPSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.100.67:8080/PersonasDUUPS/ServicioReceptorPersonaDUUPS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIORECEPTORPERSONADUUPSSERVICE_WSDL_LOCATION = url;
        SERVICIORECEPTORPERSONADUUPSSERVICE_EXCEPTION = e;
    }

    public ServicioReceptorPersonaDUUPSService() {
        super(__getWsdlLocation(), SERVICIORECEPTORPERSONADUUPSSERVICE_QNAME);
    }

    public ServicioReceptorPersonaDUUPSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIORECEPTORPERSONADUUPSSERVICE_QNAME, features);
    }

    public ServicioReceptorPersonaDUUPSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIORECEPTORPERSONADUUPSSERVICE_QNAME);
    }

    public ServicioReceptorPersonaDUUPSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIORECEPTORPERSONADUUPSSERVICE_QNAME, features);
    }

    public ServicioReceptorPersonaDUUPSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioReceptorPersonaDUUPSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioReceptorPersona
     */
    @WebEndpoint(name = "ServicioReceptorPersonaDUUPSPort")
    public ServicioReceptorPersona getServicioReceptorPersonaDUUPSPort() {
        return super.getPort(new QName("http://impl.servicioreceptorpersonaduups.sdm.com/", "ServicioReceptorPersonaDUUPSPort"), ServicioReceptorPersona.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioReceptorPersona
     */
    @WebEndpoint(name = "ServicioReceptorPersonaDUUPSPort")
    public ServicioReceptorPersona getServicioReceptorPersonaDUUPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.servicioreceptorpersonaduups.sdm.com/", "ServicioReceptorPersonaDUUPSPort"), ServicioReceptorPersona.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIORECEPTORPERSONADUUPSSERVICE_EXCEPTION!= null) {
            throw SERVICIORECEPTORPERSONADUUPSSERVICE_EXCEPTION;
        }
        return SERVICIORECEPTORPERSONADUUPSSERVICE_WSDL_LOCATION;
    }

}
