
package co.gov.movilidadbogota.ws.duups;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import co.gov.movilidadbogota.web.servicioreceptorpersonaduups.ConfirmacionRecibo;
import co.gov.movilidadbogota.web.servicioreceptorpersonaduups.NotificacionPersona;
import co.gov.movilidadbogota.web.servicioreceptorpersonaduups.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioReceptorPersona", targetNamespace = "http://servicioreceptorpersonaduups.sdm.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioReceptorPersona {


    /**
     * 
     * @return
     *     returns com.sdm.servicioreceptorpersonaduups.ConfirmacionRecibo
     */
    @WebMethod
    @WebResult(partName = "return")
    public ConfirmacionRecibo testAutenticacion();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sdm.servicioreceptorpersonaduups.ConfirmacionRecibo
     */
    @WebMethod
    @WebResult(partName = "return")
    public ConfirmacionRecibo registroPersonaUbicabilidad(
        @WebParam(name = "arg0", partName = "arg0")
        NotificacionPersona arg0);

}
